from dataclasses import dataclass, field
from typing import Optional, List, Dict

# ── 1. Research Contracts ───────────────────────────────────────────────────

@dataclass
class ResearchBrief:
    product_context: str
    targeted_query: str        # Generated by supervisor
    depth: str = "quick"
    memory_context: str = ""
    urls: List[str] = field(default_factory=list)

@dataclass
class DomainResult:
    domain: str
    findings: str = ""
    raw_signals: List[str] = field(default_factory=list)
    citations: List[dict] = field(default_factory=list)
    confidence_score: float = 0.0
    error: Optional[str] = None

@dataclass
class SynthesisOutput:
    summary: str
    top_opportunities: List[str]
    top_risks: List[str]
    recommended_actions: List[str]
    domains_run: List[str]
    domains_failed: List[str]
    competitive_map: Dict = field(default_factory=dict)
    citations: List[dict] = field(default_factory=list)

# ── 2. Generation Contracts ─────────────────────────────────────────────────

@dataclass
class GenerationBrief:
    product_context: str
    target_segment: str
    research_summary: str
    confirmed_hypotheses: List[str] = field(default_factory=list)
    failed_angles: List[str] = field(default_factory=list)
    user_query: str = ""

@dataclass
class EmailTouch:
    subject: str
    body: str
    cta: str

@dataclass
class EmailVariant:
    id: str
    angle: str
    hypothesis: str
    signal_reference: str
    touch_1: EmailTouch
    touch_2: EmailTouch
    touch_3: EmailTouch

@dataclass
class LinkedInPost:
    id: str
    angle: str
    hypothesis: str
    signal_reference: str
    hook: str
    body: str
    cta: str
    hashtags: List[str]
    image_prompt: str
    image_url: Optional[str] = None

@dataclass
class BattleCard:
    signal_reference: str
    us_label: str
    them_label: str
    us_points: List[str]
    them_points: List[str]
    gap_statement: str
    key_differentiator: str

@dataclass
class Flyer:
    signal_reference: str
    headline: str
    subheadline: str
    bullet_points: List[str]
    social_proof: str
    cta: str
    image_prompt: str
    image_url: Optional[str] = None

# ── 3. Feedback & Memory Contracts ──────────────────────────────────────────

@dataclass
class FeedbackAnalysis:
    hypothesis: str
    confirmed: bool
    segment: str
    failed_angle: Optional[str] = None
    best_channel: Optional[str] = None
    confidence: str = "medium"
    rule_for_next_cycle: str = ""